const test=require('node:test');const assert=require('node:assert/strict');
const {ReviewController}=require('../../tm_api/ui/review.js');
function view(intent='apply',disabled=false){return {review_ui:true,backend:'v24',display_profile:{settings:{selected_button_style:'solid_blue'}},question:{id:'q',revision:2,title:'Материалы',options:[{label:'Добавить в дела',intent,disabled,answer:{review_id:'q',revision:2,focus_version:3,action_id:'add'}}]}};}
function make(handler){const calls=[];const bridge={uuid:()=> 'fixed0000000000000001',context:async()=>{},message:async text=>{calls.push(['message',text]);return{};},tool:async(name,args)=>{calls.push([name,args]);return handler(name,args);}};const c=new ReviewController(bridge,()=>{});c.snapshot(view());return {c,calls};}
test('generic click sends actual mutation-bound action and single confirmation',async()=>{const h=make(n=>n==='answer_review_item'?{decision_saved:true}:{review_ui:true,question:null});await h.c.choose(0);const write=h.calls.find(x=>x[0]==='answer_review_item');assert.equal(write[1].answer.confirmed,true);assert.equal(write[1].answer.action_id,'add');assert.equal(write[1].answer.confirmation_ref,'widget:'+write[1].request_key);assert.equal(h.calls.filter(x=>x[0]==='answer_review_question').length,0);assert.equal(h.c.state.view.question,null);});
test('generic timeout reuses identical key and exact confirmation',async()=>{let attempts=0;const h=make(n=>{if(n==='answer_review_item'){if(!attempts++)throw Error('lost');return {decision_saved:true};}return {review_ui:true,question:null};});await h.c.choose(0);await h.c.choose(0);await h.c.retry();const writes=h.calls.filter(x=>x[0]==='answer_review_item');assert.equal(writes.length,2);assert.deepEqual(writes[0],writes[1]);assert.equal(h.calls.filter(x=>x[0]==='message').length,1);});
test('generic clarify stays on same question',async()=>{const h=make(()=>({decision_saved:true}));h.c.state.view=view('clarify');await h.c.choose(0);assert.equal(h.c.state.waiting,true);assert.equal(h.c.state.view.question.id,'q');assert.equal(h.calls.filter(x=>x[0]==='show_review_question').length,0);});
test('expired preview cannot be clicked',async()=>{const h=make(()=>{throw Error('must not execute');});h.c.state.view=view('apply',true);await h.c.choose(0);assert.deepEqual(h.calls,[]);});
test('generic effect never repeats when only next-card fetch failed',async()=>{let reads=0;const h=make(n=>{if(n==='answer_review_item')return{decision_saved:true};if(!reads++)throw Error('read lost');return{review_ui:true,question:null};});await h.c.choose(0);await h.c.retry();assert.equal(h.calls.filter(x=>x[0]==='answer_review_item').length,1);});
